### ISSUE TITLE
Review loop

### ISSUE THREAD

**Issue by rsirvent** [Minimega12121/COMPSs-Reproducibility-Service#1]
https://github.com/Minimega12121/COMPSs-Reproducibility-Service/blob/d12599e48e4a24e12b82aa46914d24803261d9b6/__main__.py#L33

This loop does not make sense: iterate through all files/directories just to assign the last one.

**Comment by Minimega12121** [comment]
Actually the Workflow folder is only supposed to have a single crate folder/directory so it just saves first one and breaks out of the in O(1).
I see this can be improved by directly extracting the 0th index I'll fix this in the next commit.

**Comment by Minimega12121** [comment]
like this self.crate_directory = os.path.join(self.workflow_folder, os.listdir(self.workflow_folder)[0]). This would be much better

**Comment by Minimega12121** [comment]
I'll add this with the next commit it'll resolve the bad use of syntax: 
` self.crate_directory = os.path.join(self.workflow_folder, os.listdir(self.workflow_folder)[0])`
