### ISSUE TITLE
Use of getcwd()

### ISSUE THREAD

**Issue by rsirvent** [Minimega12121/COMPSs-Reproducibility-Service#2]
The new execution of the application should be in a new sub-directory, rather than in getcwd(), since the directory where the RS is invoked can have files already, and it can be a risk to overwrite things from the user.

https://github.com/Minimega12121/COMPSs-Reproducibility-Service/blob/d12599e48e4a24e12b82aa46914d24803261d9b6/__main__.py#L64

**Comment by Minimega12121** [comment]
I agree and I will change the main program inside a `src/`
currently it works by creating a set of initial files and set of files that are in the cwd after the execution and moves
 `initial_files - final_files` into result so there should be no problem.
For now it will not be a problem I'll fix it in the upcoming weeks as this part of a code is a bit complicated so it'll take time to change the paths.
